const skins = [

    "Dual Berettas | Cobalt Quartz",
    "M4A1-S | Nitro",
    "Tec-9 | Red Quartz",
    "MP5-SD | Lab Rats",

    // "Souvenir MP7 | Tall Grass (Field-Tested)",
    "Souvenir M249 | Humidor (Field-Tested)",
    "Souvenir AUG | Spalted Wood (Factory New)",
    // "Souvenir P90 | Verdant Growth (Factory New)",
    // "Souvenir FAMAS | CaliCamo (Factory New)",
    "Souvenir FAMAS | CaliCamo (Minimal Wear)",
    "Souvenir CZ75-Auto | Midnight Palm (Factory New)",
    // "Souvenir SG 553 | Desert Blossom (Field-Tested)",
    // "Souvenir CZ75-Auto | Silver (Factory New)",
    "Souvenir MP9 | Music Box (Field-Tested)",
    // "Souvenir MP9 | Old Roots (Minimal Wear)",
    // "Souvenir MP9 | Old Roots (Factory New)",
    "Souvenir P250 | Black & Tan (Field-Tested)",
    "Souvenir G3SG1 | New Roots (Field-Tested)",
    //  "Souvenir G3SG1 | Ancient Ritual (Minimal Wear)",
    // "Souvenir P2000 | Panther Camo (Factory New)",
    // "Souvenir P2000 | Panther Camo (Minimal Wear)",
    "Souvenir P2000 | Panther Camo (Field-Tested)",

    "Sticker | Evil Geniuses (Holo) | 2020 RMR",
    "Sticker | Gen.G (Holo) | 2020 RMR",
    "Sticker | FURIA (Holo) | 2020 RMR",
    "Sticker | Nemiga (Holo) | 2020 RMR",
    "Sticker | BIG (Holo) | 2020 RMR",
    "Sticker | Renegades (Holo) | 2020 RMR",
    "Sticker | OG (Holo) | 2020 RMR",
    "Sticker | Vitality (Holo) | 2020 RMR",
    "Sticker | Ninjas in Pyjamas (Holo) | 2020 RMR",

    "Tec-9 | Cracked Opal (Minimal Wear)",
    "AUG | Snake Pit (Factory New)",
    "AUG | Tom Cat (Field-Tested)",
    "AUG | Tom Cat (Minimal Wear)",
    "AUG | Triqua (Battle-Scarred)",
    "AUG | Triqua (Field-Tested)",
    "AUG | Triqua (Minimal Wear)",
    "AUG | Triqua (Well-Worn)",
    "CZ75-Auto | Distressed (Field-Tested)",
    "CZ75-Auto | Distressed (Minimal Wear)",
    "CZ75-Auto | Imprint (Minimal Wear)",
    "CZ75-Auto | Imprint (Well-Worn)",
    "Desert Eagle | Blue Ply (Battle-Scarred)",
    "Desert Eagle | Blue Ply (Field-Tested)",
    "Desert Eagle | Blue Ply (Well-Worn)",
    "Desert Eagle | Bronze Deco (Field-Tested)",
    "Dual Berettas | Cobalt Quartz (Field-Tested)",
    "Dual Berettas | Cobalt Quartz (Minimal Wear)",
    "Dual Berettas | Dualing Dragons (Well-Worn)",
    "Dual Berettas | Ventilators (Minimal Wear)",
    "G3SG1 | Hunter (Field-Tested)",
    "G3SG1 | Hunter (Minimal Wear)",
    "G3SG1 | Hunter (Well-Worn)",
    "G3SG1 | Orange Crash (Field-Tested)",
    "G3SG1 | Ventilator (Field-Tested)",
    "G3SG1 | Ventilator (Minimal Wear)",
    "Galil AR | Black Sand (Battle-Scarred)",
    "Galil AR | Black Sand (Minimal Wear)",
    "Glock-18 | Ironwork (Battle-Scarred)",
    "Glock-18 | Ironwork (Well-Worn)",
    "Glock-18 | Off World (Battle-Scarred)",
    "Glock-18 | Off World (Field-Tested)",
    "Glock-18 | Off World (Well-Worn)",
    "Glock-18 | Oxide Blaze (Minimal Wear)",
    "Glock-18 | Oxide Blaze (Field-Tested)",
    "Glock-18 | Oxide Blaze (Battle-Scarred)",
    "Glock-18 | Sacrifice (Battle-Scarred)",
    "M249 | Spectre (Field-Tested)",
    "M4A4 | Magnesium (Well-Worn)",
    "M4A4 | Choppa (Minimal Wear)",
    "M4A1-S | Mud-Spec (Field-Tested)",
    "M4A1-S | Nitro (Battle-Scarred)",
    "MAC-10 | Echoing Sands (Battle-Scarred)",
    "MAC-10 | Echoing Sands (Field-Tested)",
    "MAC-10 | Oceanic (Field-Tested)",
    "MAC-10 | Oceanic (Minimal Wear)",
    "MAC-10 | Silver (Factory New)",
    "MP5-SD | Desert Strike (Field-Tested)",
    "MP5-SD | Desert Strike (Minimal Wear)",
    "MP7 | Armor Core (Field-Tested)",
    "MP7 | Armor Core (Minimal Wear)",
    "MP7 | Cirrus (Battle-Scarred)",
    "MP7 | Urban Hazard (Minimal Wear)",
    "MP9 | Bioleak (Field-Tested)",
    "MP9 | Bioleak (Minimal Wear)",
    "MP9 | Modest Threat (Minimal Wear)",
    "MP9 | Modest Threat (Field-Tested)",
    "Negev | Dazzle (Field-Tested)",
    "Negev | Man-o'-war (Minimal Wear)",
    "Negev | Prototype (Field-Tested)",
    "Negev | Prototype (Minimal Wear)",
    "Nova | Wood Fired (Minimal Wear)",
    "P2000 | Oceanic (Field-Tested)",
    "P2000 | Oceanic (Minimal Wear)",
    "P250 | Cassette (Factory New)",
    "P250 | Valence (Battle-Scarred)",
    "P250 | Valence (Field-Tested)",
    "P90 | Grim (Battle-Scarred)",
    "P90 | Grim (Field-Tested)",
    "P90 | Grim (Minimal Wear)",
    "R8 Revolver | Bone Forged (Field-Tested)",
    "R8 Revolver | Bone Forged (Minimal Wear)",
    "R8 Revolver | Inlay (Factory New)",
    "R8 Revolver | Nitro (Minimal Wear)",
    "Sawed-Off | Fubar (Battle-Scarred)",
    "Sawed-Off | Black Sand (Field-Tested)",
    "Sawed-Off | Black Sand (Minimal Wear)",
    "Sawed-Off | Morris (Field-Tested)",
    "Sawed-Off | Origami (Field-Tested)",
    "SCAR-20 | Jungle Slipstream (Field-Tested)",
    "SSG 08 | Azure Glyph (Battle-Scarred)",
    "SSG 08 | Azure Glyph (Field-Tested)",
    "SSG 08 | Azure Glyph (Well-Worn)",
    "SG 553 | Danger Close (Field-Tested)",
    "SG 553 | Danger Close (Minimal Wear)",
    "Tec-9 | Cracked Opal (Field-Tested)",
    "Tec-9 | Cracked Opal (Well-Worn)",
    "Tec-9 | Red Quartz (Field-Tested)",
    "Tec-9 | Red Quartz (Minimal Wear)",
    "Tec-9 | Fubar (Field-Tested)",
    "Tec-9 | Fubar (Well-Worn)",
    "USP-S | Desert Tactical (Battle-Scarred)",
    "USP-S | Desert Tactical (Field-Tested)",
    "USP-S | Desert Tactical (Well-Worn)",
    "XM1014 | Slipstream (Field-Tested)",
    "XM1014 | Slipstream (Minimal Wear)"
];